### ISSUE TITLE
Patient Retention & Anti-Churn Features for Pharmacies

### ISSUE THREAD

**Issue by Qodestackr** [Qodestackr/Avaris-Health#8]
Kenyan pharmacies lose 40% of chronic patients within 6 months. Most don't track patient adherence or have systems to encourage loyalty. WhatsApp groups and "this patient usually buys X" aren't cutting it anymore.

🎯 Objectives

Reduce patient churn by 50% in pilot pharmacies
Turn one-time buyers into repeat customers
Help pharmacies move expiring stock intelligently
Make loyalty points as addictive as doom-scrolling

🛠️ Features & Acceptance Criteria
1. Loyalty Program That Actually Makes Sense
```yaml
rewards:
  chronic_meds:
    points: 10  # per 1000 KES
    bonus:
      every_3_months: 50
      conditions: "no_gaps_in_refills"
  
  general_purchase:
    points: 5  # per 1000 KES
    min_purchase: 200  # KES

redemption:
  rate: 1  # KES per point
  min_points: 100
  channels: ["mpesa", "next_purchase"]
```
Must Have:
- M-Pesa integration for instant cashback
- WhatsApp notifications for points earned
- Patient portal to check points (USSD backup when internet dies)
- Auto-expire points after 12 months (we're not M-Pesa, points can't live forever)

ROI: Loyalty programs → 25% more repeat customers. Patient adherence history = impossible to migrate.

8a: Patient Loyalty Program Engine

Auto-issue M-Pesa loyalty points for repeat purchases (e.g., "Buy ARVs 5x → Get $1 cashback").

Pharmacies configure rewards via simple YAML.

Acceptance: /loyalty/redeem API endpoint + SMS integration.

8b: Adherence Tracking & SMS Nudges

Track refill dates for chronic patients (diabetes, HIV).

Auto-send Swahili SMS: "Daktari akusaidie! Rudi Bliss kuchukua dawa yako."

Acceptance: 70%+ refill rate in pilot pharmacies.

8c: Pharmacy "Customer Health" Dashboard

Show key metrics:

Patient churn risk scores

Top 10% chronic patients needing attention

Loyalty point redemption rates

Acceptance: Pharmacies can export "at-risk" patient lists.

8d: Dynamic Discounts for Expiring Stock

AI suggests discounts on near-expiry drugs to high-risk patients.

Example: "Offer 20% off expiring insulin to diabetic patients."

Acceptance: Reduce waste by 40% in 3 months.
